apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: frontend
  namespace: app
  labels:
    name: frontend
    environment: poc 
spec:
  host: frontend
  subsets:
    - labels:
        name: frontend
        environment: poc 
      name: v1
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
