{{- range $application := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $application.name }}
spec:
  destination:
    namespace: {{ $application.namespace }}
    server: {{ $application.server }}
  source:
    path: {{ $application.path }}
    repoURL: {{ $application.repoURL }}
    targetRevision: {{ $application.repoBranch }}
    helm:
      valueFiles:
      - {{ $application.valueFile }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=false
    - Replace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  project: {{ $application.namespace }}
{{- end }}


