apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 2 }}
  template:
    metadata:
{{- with .Values.podAnnotations }}
      annotations:
{{- toYaml . | nindent 8 }}
{{- end }}
      labels:
{{- toYaml .Values.lables | nindent 8 }}
    spec:
{{- with .Values.podSecurityContext }}
      securityContext:
{{- toYaml . | nindent 8 }}
{{- end }}
      containers:
        - name: {{ .Values.name }}
{{- with .Values.securityContext }}
          securityContext:
{{- toYaml . | nindent 12 }}
{{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- with .Values.command }}
          command:
{{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.env }}
          env:
{{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.container.ports }}
          ports:
{{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.livenessProbe }}
          livenessProbe:
{{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.readinessProbe }}
          readinessProbe:
{{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.resources }}
          resources:
{{- toYaml . | nindent 12 }}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}