apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Values.service.name }}
spec:
  host: {{ .Values.service.name }}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2