apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app
spec:
  type: ClusterIP
  ports:
    - name: frontend
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend