apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend
spec:
  hosts:
    - app.mcrpv.in
  http:
  - route:
    - destination:
        host: frontend
        subset: v1
      weight: 40
    - destination:
        host: frontend
        subset: v2
      weight: 60