apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.service.name }}
spec:
  hosts:
    - {{ .Values.traffic.domain }}
  http:
  - route:
    - destination:
        host: {{ .Values.service.name }}
        subset: v1
      weight: {{ .Values.traffic.v1_weight }}
    - destination:
        host: {{ .Values.service.name }}
        subset: v2
      weight: {{ .Values.traffic.v2_weight }}